### ISSUE TITLE
Seems like my bot is runaway: Just talking to itself

### ISSUE THREAD

**Issue by databloom** [csvance/FTBot#48]
INFO:discord.http:A rate limit bucket has been exhausted

Is there a lever for lowering the responses or is this perhaps bad training data that is causing my bot to run rampant ?

**Comment by csvance** [comment]
Did you set DISCORD_USERNAME correctly in config/discord.py?

If this is not set correctly, ie: `DISCORD_USERNAME = 'SomeBot#1234'` then the bot might respond to itself.

**Comment by databloom** [comment]
Mismatching spaces in username entries !!
