### ISSUE TITLE
Python namespace collision with common module

### ISSUE THREAD

**Issue by databloom** [csvance/FTBot#49]
Hi !

I dropping your code into a docker container and used pigar to build a requirements.txt file and for some reason it pulled down common and installed it via pip3.

Took me a while to figure out why common.nlp couldn't be found.

Could you at a later date change your namespace to be a bit more exotic so other less capable python folk don't trip over this.

I'll update this with the docker container when it is up on dockerhub

**Comment by csvance** [comment]
You are right, the naming and hierarchy of modules in armchair-expert could use some work in general. I would accept a pull request for it if you have worked around it already. If not I will try to get to it sometime this week.
